### ISSUE TITLE
CEP 11: evalScript no longer executes callbacks when in iframed context

### ISSUE THREAD

**Issue by saar62097** [Inventsable/bombino#17]
When trying an app built with Bombino in AE 18.4 (Beta, prerelease) that has CEP11 embedded in it, then calling 
`window.__adobe_cep__.evalScript("app", function(r){console.log(r)});` inside the iframed app (localhost:8080) no longer executes the callback, unlike in CEP 10 and before.

I'm not sure it is related to any of the 4 points listed by Adobe [here](https://github.com/Adobe-CEP/CEP-Resources/blob/master/CEP_11.x/Documentation/CEP%2011.1%20HTML%20Extension%20Cookbook.md#migration-from-cep-10-to-cep-11) 

Are there any changes needed to apply to the config that will make JSX (extendcsript) accessible again within the iframe, including invoking the callbacks?

thnx in advance

**Comment by saar62097** [comment]
Adobe suggests using postMessage
https://github.com/Adobe-CEP/CEP-Resources/issues/364

**Comment by Inventsable** [comment]
This is fixed via #20
