### ISSUE TITLE
How to talk to host via csInterface

### ISSUE THREAD

**Issue by Jean-Zombie** [Inventsable/bombino#19]
Hey there,

I successfully set up a "bombino-vue-basic" extension template and am trying to connect to my host app (InDesign) via the `csInterface` but I struggle. 

```
<template>
  <div class="centered">
    <img alt="Vue logo" src="../assets/logo.png" />
    <h1 class="centered">{{ msg }}</h1>
    <div class="button" @click="test()">Click</div>
  </div>
</template> 

<script>
export default {
  name: "HelloWorld",
  props: {
    msg: String
  },
  methods: {
    test() {
      this.app.csInterface.evalScript(alert("Inside of host"));  // I'd expected this to work
      // alert("Outside of host");  // this code works if not commented out
    }
  }
};
</script>
<!-- code cut of for clarity -->
```

I have to admit I am punching way above my weight here, since I only ever used plain `.jsx` scripts before. But since the bombino templating works so well, I hoped to get into it more.

Is there maybe a simple test file for a working `csInterface` implementation?

Edit:
Console log shows `Cannot read property 'evalScript' of undefined` so `csInterface` is not assigned it seems.

**Comment by Inventsable** [comment]
> Your explanation of the impact of the new CORS is very insightful. I regret not opening the issue on the main bombino repo for more visibility for others.

No worries, I've transferred it to the main bombino repo.

---

I've [published the new version of evalScript](https://github.com/Inventsable/workaround) to npm as the package `workaround` (which I was shocked to see wasn't already taken), but have yet to implement the required event listeners in the templates (though I've already done this in my own projects and have proven it to work). I'll be fixing all templates within the next few days, likely tomorrow.

**Comment by Jean-Zombie** [comment]
I am closing this, since the `workaround` package did solve my issue.
