### ISSUE TITLE
How to use libs such as ffmpeg, opencv etc

### ISSUE THREAD

**Issue by micodeyt** [Inventsable/bombino#2]
Hello !

I've started CEP development with your super cool generator (thanks so much for creating that).
I was wondering if using libs such as ffmpeg, youtube-dl, or opencv in Adobe CEP would be possible ?
For what I understand Adobe uses NW.js. I think I would have to make static builds of the binaries I want to use for Windows & Mac.
But then how would you create 2 builds of the Extension with the right binaries in it ? Is that even recommended ?

Thanks !

**Comment by micodeyt** [comment]
(if you have any example of open source Extensions doing that, it would be very helpful)

**Comment by Inventsable** [comment]
Hello! Sorry for the late reply, I've not needed to do this personally but I'm checking with a few people to get an answer for you. Thanks for using the library!

**Comment by adamplouff** [comment]
I'm currently using FFMPEG in a project. I've added the mac/win ffmpeg executables to the project that brings the ZXP file size to around 45mb. It's using *exec* to run ffmpeg in the command line. 

`import util, { log } from 'util'
const exec = util.promisify(require('child_process').exec);

let ffmpeg = this.csInterface.getSystemPath(SystemPath.EXTENSION) + '/src/ffmpeg/ffmpeg'
let fileIn = renderData.layerName + '.' + renderData.ext
let fileOut = renderData.layerName + '.mp4'

async function ffmpegCompress() {
                    const { stdout, stderr } = await exec('"'+ ffmpeg +'" -y -i "'+ path + '/' + fileIn +'" -c:v libx264 -preset slow -crf 6 -vf yadif -strict -2 -pix_fmt yuv420p "'+ path + '/' + fileOut +'"');
                    console.error('stderr:', stderr);
                    return {
                        fileIn: path + '/' + fileIn,
                        path: path + '/' + fileOut,
                        layerName: renderData.layerName,
                        framelength: renderData.framelength,
    }
}`

**Comment by Inventsable** [comment]
In addition to what Adam's said, I posted this to the [Adobe Devs Slack](https://adobedevs.slack.com/) and got an answer from @ericdrobinson:

> @Tom Scharstein You can’t build static native stuff targeting the NW.js core in CEP. Adobe doesn’t give us enough to do so. However, that’s not what the user is doing: they’re simply including the static FFMPEG binary and executing it with `exec`. That is doable.

> His real question is this: 

> But then how would you create 2 builds of the Extension with the right binaries in it ? Is that even recommended ?

> You would still just make the one “build”. However, you would probably do this:

> 1) put the Windows static ffmpeg binary in `bin\ffmpeg\win`
> 2) put the macOS static ffmpeg binary in `bin/ffmpeg/mac`

> Then you would make sure that the path you specify switches between the two based upon the executing environment.

Accessing the execution environment inside a .vue file can be done via `process.platform` or `cep_node.process.platform` if needed for certain binaries though Adam's also solved it above without doing so for ffmpeg

**Comment by adamplouff** [comment]
I have both of the mac and win versions sitting in src/ffmpeg and tested on mac and win with no trouble. It seems to auto target the correct version without needing to test for which version. I guess thats just a part of *exec*.

**Comment by micodeyt** [comment]
Thank you so much guys, that really helps !
