### ISSUE TITLE
New CORS policy for ILST >=25.3 and newest versions of other apps break DEVELOPMENT context

### ISSUE THREAD

**Issue by Inventsable** [Inventsable/bombino#20]
I've yet to implement the [solution for this in the templates](https://github.com/Inventsable/workaround) but just in case any one has an issue with old versions of the panel in the future (if a template was generated prior to this fix and you're just now coming back to it or notice a bombino panel failing on evalScript returns in new versions of the apps) there is a new CORS policy in Adobe apps which blocks `<iframe>` elements from accessing `evalScript` return values, which is critical for bombino because the DEVELOPER context is done through an iframe. For instance, in the code below:

```js
let result = await evalScript(`
  (function() {
    alert("Hello world");     // This will always run in both contexts
    return app.name;          // This will only run in production (for now)
  }())
`)
console.log(result);          // This will only work/run in production context
console.log("Goodbye");       // This will always run in both contexts
```

CEP will cause a silent failure in new versions of apps when attempting to return an evalScript value from DEVELOPER context, but this has no affect on PRODUCTION. You will notice that, in any panel which relies on returning values from an evalScript call, DEVELOPER context will be broken.

I'll be updating all templates within the next two days as I've already fixed and addressed this in my own projects, but wanted to document this for posterity. Thanks for using bombino! 👍

**Comment by Inventsable** [comment]
Fixed though I'll wait a while to close it in case I've overlooked any templates, any one points out my workaround has issues, and for general visibility.

**Comment by Inventsable** [comment]
~~**For CEP <= 10 to 11 migration:**~~

- ~~All instances of `evalScript` should now be imported from the `workaround` package instead of `cluecumber` or `brutalism` via `npm i workaround` then `import { evalScript } from "workaround"`~~
- ~~`./public/index-dev.html` should [include the following lines](https://github.com/Inventsable/bombino-vue-basic/blob/master/public/index-dev.html#L6-L10)~~
- ~~Include a new file in `./public` named `createEventChain.js` with [the following code](https://github.com/Inventsable/bombino-vue-basic/blob/master/public/createEventChain.js)~~

~~This should be an all inclusive solution to the new CORS policy regardless of context and even iframe depth, though it should be noted that if you include any `window.addEventListener` with a `capture: true` parameter, you may interfere with the listener constructed on `evalScript` invocation and prevent propagation. This is unlikely to happen unless you're using `evalScript` within more than 1 depth of iframe (like when in DEVELOPER context of a panel which itself already uses a frame to serve web content) and have a listener high in the DOM tree of the web content.~~

**Comment by Inaztm** [comment]
Hello. In development mode, I try to execute in parent window
```
__adobe_cep __. evalScript ('typeof importTimeline', (res) => console.log (res))
```
![image](https://user-images.githubusercontent.com/9611099/134868240-c05ab7b4-1485-413f-a7eb-a5317dc09f14.png)
but as a result I get "undefined".
Question: Scripts (/src/host/PPRO/host.jsx) are not loaded in development mode or are they loaded inside an iframe?

**Comment by Inaztm** [comment]
Hello. In development mode, trying to execute
```
__adobe_cep __. evalScript ('typeof importTimeline', (res) => console.log (res))
```
![image](https://user-images.githubusercontent.com/9611099/134876991-042e8da2-bfa0-4bd7-ac9f-4a7e9bfe883f.png)
but as a result I get "undefined".
Question: Skips are not loaded in development mode or are they loaded inside an iframe?

**Comment by Inventsable** [comment]
This issue should be resolved as of recently. An all-inclusive solution and access to iframes can be granted via the following lines in manifest.xml:

```xml
<CEFCommandLine>
    <Parameter>--disable-features=SameSiteByDefaultCookies,CookiesWithoutSameSiteMustBeSecure,NetworkService</Parameter>
    <Parameter>--disable-site-isolation-trials</Parameter>          
    <Parameter>--enable-nodejs</Parameter>
    <Parameter>--mixed-context</Parameter>
</CEFCommandLine>
```

Notice the two `<Parameter>` values at the top, adding these should allow the same behavior in CEP11 as all versions of bombino prior.

**Comment by Inventsable** [comment]
Going to close this as all templates have been updated and this should never be an issue. Migration for templates prior to CEP11 should be done with adding the above manifest `<Parameters>`, though migration for any templates created in the brief period that `workaround` was being suggested will need to:

- Delete references to `createEventChain.js` found in `./public/index.html` and `./public/index-dev.html`
- Delete `./public/createEventChain.js`
- Run `npm i brutalism@latest` (if applicable)
- Ensure that any `evalScript` imports are from `cluecumber` or `brutalism` and that none exist which are referenced from `workaround` (as this requires a messaging system that will no longer exist in the panel)
