### ISSUE TITLE
No such file or directory  AND can not find the .zxp in ./archive/

### ISSUE THREAD

**Issue by tiandiyiqi** [Inventsable/bombino#7]
⠹ Running ZXPSignCmd for you...
./ZXPSignCmd -selfSignedCert US NY SomeOrg SomeName hello-world ./Hello-World/archive/temp1.p12
/bin/sh: ./ZXPSignCmd: No such file or directory
⠴ Running ZXPSignCmd for you...
./ZXPSignCmd -sign ./Hello-World_1.0.0-tmp ./Hello-World/archive/Hello-World_1.0.0.zxp ./Hello-World/archive/temp1.p12 hello-world -tsa http://time.certum.pl
/bin/sh: ./ZXPSignCmd: No such file or directory
⠧ Running ZXPSignCmd for you.../bin/sh: ./ZXPSignCmd: No such file or directory

./ZXPSignCmd -verify ./Hello-World/archive/Hello-World_1.0.0.zxp -certinfo
/bin/sh: ./ZXPSignCmd: No such file or directory

      ✔ SIGNING COMPLETE  

      HELLO-WORLD_1.0.0.ZXP IS READY  

    You can find it in ./archive/Hello-World_1.0.0.zxp

**Comment by Inventsable** [comment]
Hi, please provide more information like what directory you're running the command from, what template, what version.

**Comment by tiandiyiqi** [comment]
directory: c:\bom\Hello-World\
template: bombino-brutalism-basic
bombino version: 1.3
`
@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@
@@@@@@@@     @@@@     @@@   @@@   @@@     @@@  @@%   @@  @@@     .@@@@@@@@@
@@@@@@@@  @  @@@  @@@  @@    @@   @@@  @  @@@  @@% &  @  @@  #@@   @@@@@@@@
@@@@@@@@  @  .@@  @@@  @@  @ .    @@@  @   @@  @@% @@    @@  @@@   @@@@@@@@
@@@@@@@@     @@@.     @@@  @.  @  @@@     @@@  @@% @@@   @@@      @@@@@@@@@
@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@

   WELCOME TO BOMBINO

? What would you like to do? Create a new Adobe panel
? Name of panel? Hello World
? Use your custom templates or bombino defaults? Static (no internet)

   ✔ 9 TEMPLATES AVAILABLE

? What tooling preset should be used? Vue-CLI
? Which Vue-CLI template should be used? bombino-brutalism-basic (Vue-CLI, bruta

lism, basic utilities)
? Host apps to include: (Press <space> to select, <a> to toggle all, <i> to inve
? Host apps to include: Illustrator
? Base CEF Port (between 1024 and 65534) 8888
? Run npm install for you? Yes
   ⠲ Downloading template from Inventsable/bombino-brutalism-basic...
   ✔ DOWNLOAD COMPLETE

   ⠋ Correcting placeholders...
   ✔ CORRECTIONS COMPLETE
   ⠚ Running npm install for you...npm WARN deprecated request@2.88.2: request h
as been deprecated, see https://github.com/request/request/issues/3142
   ⠞ Running npm install for you...npm WARN deprecated chokidar@2.1.8: Chokidar
2 will break on node v14+. Upgrade to chokidar 3 with 15x less dependencies.
   ⠋ Running npm install for you...npm WARN deprecated urix@0.1.0: Please see ht
tps://github.com/lydell/urix#deprecated
npm WARN deprecated resolve-url@0.2.1: https://github.com/lydell/resolve-url#dep
recated
   ⠚ Running npm install for you...
> yorkie@2.0.0 install c:\bom\Hello-World\node_modules\yorkie
> node bin/install.js

   ⠞ Running npm install for you...setting up Git hooks
can't find .git directory, skipping Git hooks installation
   ⠦ Running npm install for you...
> core-js@3.6.5 postinstall c:\bom\Hello-World\node_modules\core-js
> node -e "try{require('./postinstall')}catch(e){}"

   ⠴ Running npm install for you...Thank you for using core-js ( https://github.
com/zloirock/core-js ) for polyfilling JavaScript standard library!

The project needs your help! Please consider supporting of core-js on Open Colle
ctive or Patreon:
> https://opencollective.com/core-js
> https://www.patreon.com/zloirock

Also, the author of core-js ( https://github.com/zloirock ) is looking for a goo
d job -)


> ejs@2.7.4 postinstall c:\bom\Hello-World\node_modules\ejs
> node ./postinstall.js

   ⠲ Running npm install for you...Thank you for installing EJS: built with the
Jake JavaScript build tool (https://jakejs.com/)

   ⠞ Running npm install for you...npm WARN notsup Unsupported engine for watchp
ack-chokidar2@2.0.0: wanted: {"node":"<8.10.0"} (current: {"node":"14.1.0","npm"
:"6.14.4"})
npm WARN notsup Not compatible with your version of node/npm: watchpack-chokidar
2@2.0.0
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@~2.1.2 (node_modules\ch
okidar\node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@
2.1.3: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"}
)
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@^1.2.7 (node_modules\wa
tchpack-chokidar2\node_modules\chokidar\node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@
1.2.13: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"
})
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@^1.2.7 (node_modules\we
bpack-dev-server\node_modules\chokidar\node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@
1.2.13: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"
})

added 1354 packages from 877 contributors and audited 1366 packages in 39.594s
   ⠚ Running npm install for you...
47 packages are looking for funding
  run `npm fund` for details

found 1 low severity vulnerability
  run `npm audit fix` to fix them, or `npm audit` for details
   ⠞ Running npm install for you...
   ✔ INSTALL COMPLETE

   ╭──────────────────────────╮
   │                          │
   │   HELLO-WORLD IS READY   │
   │                          │
   ╰──────────────────────────╯

Ready to get started? Run the following commands:

   cd Hello-World
   npm run serve

Then launch your desired host app and find in Window > Extensions

You can use npm run help at any time inside the panel to see a full list of comm
ands.


c:\bom>cd Hello-World

c:\bom\Hello-World>npm run help

> hello-world@0.1.0 help c:\bom\Hello-World
> bombino-cmd help


   Welcome! You can run these commands at any time:

 VUE  npm run serve — Run the development server (DEVELOPER)
 VUE  npm run build — Compile to /dist/ directory (PRODUCTION)
 CEP  npm run switch — Switch between DEVELOPER and PRODUCTION
 CEP  npm run update — Update the panel's version
 CEP  npm run register — Register the info to be used in npm run sign
 CEP  npm run sign — Stage, sign, and certify panel with result as ./archive/He
llo-World1.0.0.zxp

   - Documentation per template can be found at the generator repo here:
     https://github.com/Inventsable/bombino#templates

   - An outline of how to use this workflow and what each command does can be fo
und here:
     https://github.com/Inventsable/bombino-commands#commands
     https://github.com/Inventsable/bombino-commands#usage


c:\bom\Hello-World>npm run build

> hello-world@0.1.0 build c:\bom\Hello-World
> vue-cli-service build


\  Building for production...

 DONE  Compiled successfully in 13056ms                              下午3:39:31


  File                                   Size              Gzipped

  dist\js\chunk-vendors.abc780e3.js      347.72 KiB        94.08 KiB
  dist\CSInterface.js                    39.13 KiB         9.74 KiB
  dist\js\app.6beaeedd.js                6.34 KiB          2.32 KiB
  dist\css\chunk-vendors.6f493120.css    232.41 KiB        40.35 KiB
  dist\css\app.67c89438.css              0.79 KiB          0.39 KiB

  Images and other types of assets omitted.

 DONE  Build complete. The dist directory is ready to be deployed.
 INFO  Check out deployment instructions at https://cli.vuejs.org/guide/deployme
nt.html


c:\bom\Hello-World>npm run switch

> hello-world@0.1.0 switch c:\bom\Hello-World
> bombino-cmd switch

 CEP   Didn't mean to do that? Use npm run help to see a full list of commands

 CEP   Hello-World1.0.0 is in DEVELOPER

? Would you like to switch to PRODUCTION? Yes

    ✔  CONTEXT SWITCHED TO PRODUCTION

  PRODUCTION: Ready for npm run serve or npm run sign.


c:\bom\Hello-World>npm run register

> hello-world@0.1.0 register c:\bom\Hello-World
> bombino-cmd register

 CEP   Didn't mean to do that? Use npm run help to see a full list of commands

✘  No user data was found! It will default to US NY SomeOrg
? Country Code US
? State or Province NY
? Organization SomeOrg
? Common name test

   ✔  Config has been saved to ./.certinfo
   Self-signed certificates via npm run sign will use this data!


c:\bom\Hello-World>npm run sign

> hello-world@0.1.0 sign c:\bom\Hello-World
> bombino-cmd sign

 CEP   Didn't mean to do that? Use npm run help to see a full list of commands

 CEP   Signing Hello-World_1.0.0!

   Be sure to run npm run register prior to this command.
   You can add any valid regex or phrases to ./.certignore to exclude them from
staging.

? Password for certificate 123456
? Create a ZIP aswell? Yes
- Staging temp files...
   Excluding: .gitignore
   Excluding: node_modules

      ✔ STAGING COMPLETE

/ Running ZXPSignCmd for you...
ZXPSignCmd -selfSignedCert US NY SomeOrg test 123456 ./Hello-World/archive/temp1
.p12
'ZXPSignCmd' �����ڲ����ⲿ���Ҳ���ǿ����еĳ���
���������ļ���
/ Running ZXPSignCmd for you...
ZXPSignCmd -sign ./Hello-World_1.0.0-tmp ./Hello-World/archive/Hello-World_1.0.0
.zxp ./Hello-World/archive/temp1.p12 123456 -tsa http://time.certum.pl
'ZXPSignCmd' �����ڲ����ⲿ���Ҳ���ǿ����еĳ���
���������ļ���
/ Running ZXPSignCmd for you...'ZXPSignCmd' �����ڲ����ⲿ���Ҳ���ǿ����еĳ���
���������ļ���

ZXPSignCmd -verify ./Hello-World/archive/Hello-World_1.0.0.zxp -certinfo
'ZXPSignCmd' �����ڲ����ⲿ���Ҳ���ǿ����еĳ���
���������ļ���

      ✔ SIGNING COMPLETE

      HELLO-WORLD_1.0.0.ZXP IS READY

    You can find it in ./archive/Hello-World_1.0.0.zxp


c:\bom\Hello-World>


`

**Comment by Inventsable** [comment]
Do you have [ZXPSignCmd.exe](https://github.com/Adobe-CEP/CEP-Resources/tree/master/ZXPSignCMD/4.1.1) in the `c:\bom\` directory?

**Comment by tiandiyiqi** [comment]
Oh, I get it .
I run "npm install zxp-sign-cmd -s" and  copy the ZXPSignCmd to the c:\bom\Hello-World
It is wrong

**Comment by Inventsable** [comment]
Hi, I actually don't use the npm package in the templates and there's no need to include or install that package. [In the first line of the link to the commands](https://github.com/Inventsable/bombino-commands#npm-run-sign) (shown on the help command and linked in both the repo and template) for `npm run sign` I note this:

> 🚩 This command only works if ZXPSignCmd.exe is located in the parent folder (eg .../cep/extensions/)

It relies on [ZXPSignCmd.exe](https://github.com/Adobe-CEP/CEP-Resources/tree/master/ZXPSignCMD/4.1.1) being in the parent to the extension's root. If the node package works then great! But I'm not sure I'd go so far as to say anything in the generator is wrong.
