### ISSUE TITLE
require not defined error running in Chrome window

### ISSUE THREAD

**Issue by tiandiyiqi** [Inventsable/bombino#8]
external "events"?7a7e:1 Uncaught ReferenceError: require is not defined
    at eval (external "events"?7a7e:1)
    at Object.events (app.js:1139)
    at __webpack_require__ (app.js:854)
    at fn (app.js:151)
    at eval (emitter.js?a6bd:1)
    at Object../node_modules/webpack/hot/emitter.js (chunk-vendors.js:6015)
    at __webpack_require__ (app.js:854)
    at fn (app.js:151)
    at eval (dev-server.js?6895:50)
    at Object../node_modules/webpack/hot/dev-server.js (chunk-vendors.js:6004)
popup.js:15 Uncaught TypeError: Cannot read property 'onUpdated' of undefined
    at popup.js:15

<img width="592" alt="error" src="https://user-images.githubusercontent.com/17092712/85489707-f8e26d80-b602-11ea-9a73-494c6e73dd2b.png">

` node scripts/postinstall

npm WARN @grpc/grpc-js@1.1.1 requires a peer of google-auth-library@5.x || 6.x but none is installed. You must install peer dependencies yourself.

+ bombino@1.3.0
added 6 packages from 3 contributors, removed 1120 packages and updated 253 packages in 17.185s
cymmetriktangcom:bom tangqihua$ bombino

@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@
@@@@@@@@     @@@@     @@@   @@@   @@@     @@@  @@%   @@  @@@     .@@@@@@@@@
@@@@@@@@  @  @@@  @@@  @@    @@   @@@  @  @@@  @@% &  @  @@  #@@   @@@@@@@@
@@@@@@@@  @  .@@  @@@  @@  @ .    @@@  @   @@  @@% @@    @@  @@@   @@@@@@@@
@@@@@@@@     @@@.     @@@  @.  @  @@@     @@@  @@% @@@   @@@      @@@@@@@@@
@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@

   WELCOME TO BOMBINO 

? What would you like to do? Create a new Adobe panel
? Name of panel? TangApp
? Use your custom templates or bombino defaults? Static (no internet)

   ✔ 9 TEMPLATES AVAILABLE 

? What tooling preset should be used? Vue-CLI
? Which Vue-CLI template should be used? bombino-brutalism-vuex (Vue-CLI, brutal
ism, router, vuex)
? Host apps to include: Illustrator
? Base CEF Port (between 1024 and 65534) 8888
? Run npm install for you? Yes
   ⠞ Downloading template from Inventsable/bombino-brutalism-vuex...
   ✔ DOWNLOAD COMPLETE 

   ⠋ Correcting placeholders...
   ✔ CORRECTIONS COMPLETE 
   ⠋ Running npm install for you...npm WARN deprecated request@2.88.2: request has been deprecated, see https://github.com/request/request/issues/3142
   ⠙ Running npm install for you...npm WARN deprecated chokidar@2.1.8: Chokidar 2 will break on node v14+. Upgrade to chokidar 3 with 15x less dependencies.
   ⠚ Running npm install for you...
> fsevents@1.2.13 install /Library/Application Support/Adobe/CEP/extensions/bom/TangApp/node_modules/watchpack-chokidar2/node_modules/fsevents
> node install.js

   ⠲ Running npm install for you...  SOLINK_MODULE(target) Release/.node
   ⠞ Running npm install for you...  CXX(target) Release/obj.target/fse/fsevents.o
   ⠓ Running npm install for you...  SOLINK_MODULE(target) Release/fse.node
   ⠋ Running npm install for you...
> fsevents@1.2.13 install /Library/Application Support/Adobe/CEP/extensions/bom/TangApp/node_modules/webpack-dev-server/node_modules/fsevents
> node install.js

   ⠓ Running npm install for you...  SOLINK_MODULE(target) Release/.node
  CXX(target) Release/obj.target/fse/fsevents.o
   ⠓ Running npm install for you...  SOLINK_MODULE(target) Release/fse.node
   ⠋ Running npm install for you...
> yorkie@2.0.0 install /Library/Application Support/Adobe/CEP/extensions/bom/TangApp/node_modules/yorkie
> node bin/install.js

   ⠙ Running npm install for you...setting up Git hooks
can't find .git directory, skipping Git hooks installation
   ⠞ Running npm install for you...
> core-js@3.6.5 postinstall /Library/Application Support/Adobe/CEP/extensions/bom/TangApp/node_modules/core-js
> node -e "try{require('./postinstall')}catch(e){}"

   ⠖ Running npm install for you...Thank you for using core-js ( https://github.com/zloirock/core-js ) for polyfilling JavaScript standard library!

The project needs your help! Please consider supporting of core-js on Open Collective or Patreon: 
> https://opencollective.com/core-js 
> https://www.patreon.com/zloirock 

Also, the author of core-js ( https://github.com/zloirock ) is looking for a good job -)

> ejs@2.7.4 postinstall /Library/Application Support/Adobe/CEP/extensions/bom/TangApp/node_modules/ejs
> node ./postinstall.js

   ⠦ Running npm install for you...Thank you for installing EJS: built with the Jake JavaScript build tool (https://jakejs.com/)

   ⠲ Running npm install for you...npm WARN notsup Unsupported engine for watchpack-chokidar2@2.0.0: wanted: {"node":"<8.10.0"} (current: {"node":"12.16.1","npm":"6.13.4"})
npm WARN notsup Not compatible with your version of node/npm: watchpack-chokidar2@2.0.0

added 1359 packages from 886 contributors in 30.277s
   ⠚ Running npm install for you...
44 packages are looking for funding
  run `npm fund` for details

   ⠞ Running npm install for you...
   ✔ INSTALL COMPLETE 

   ╭──────────────────────╮
   │                      │
   │   TANGAPP IS READY   │
   │                      │
   ╰──────────────────────╯

Ready to get started? Run the following commands:

   cd TangApp
   npm run serve

Then launch your desired host app and find in Window > Extensions

You can use npm run help at any time inside the panel to see a full list of commands.

cymmetriktangcom:bom tangqihua$ cd TangApp
cymmetriktangcom:TangApp tangqihua$ npm run serve

> tangapp@0.1.0 serve /Library/Application Support/Adobe/CEP/extensions/bom/TangApp
> vue-cli-service serve

 INFO  Starting development server...
40% building 217/264 modules 47 active ...es/core-js/internals/dom-iterables.jsYou did not set any plugins, parser, or stringifier. Right now, PostCSS does nothing. Pick plugins for your case on https://www.postcss.parts/ and use them in postcss.config.js.
63% building 444/478 modules 34 active ...ct-get-own-property-names-external.jsYou did not set any plugins, parser, or stringifier. Right now, PostCSS does nothing. Pick plugins for your case on https://www.postcss.parts/ and use them in postcss.config.js.
65% building 491/532 modules 41 active ...odules/core-js/internals/is-regexp.jsYou did not set any plugins, parser, or stringifier. Right now, PostCSS does nothing. Pick plugins for your case on https://www.postcss.parts/ and use them in postcss.config.js.
65% building 492/532 modules 40 active ...odules/core-js/internals/is-regexp.jsYou did not set any plugins, parser, or stringifier. Right now, PostCSS does nothing. Pick plugins for your case on https://www.postcss.parts/ and use them in postcss.config.js.
65% building 493/532 modules 39 active ...odules/core-js/internals/is-regexp.jsYou did not set any plugins, parser, or stringifier. Right now, PostCSS does nothing. Pick plugins for your case on https://www.postcss.parts/ and use them in postcss.config.js.
65% building 494/532 modules 38 active ...odules/core-js/internals/is-regexp.jsYou did not set any plugins, parser, or stringifier. Right now, PostCSS does nothing. Pick plugins for your case on https://www.postcss.parts/ and use them in postcss.config.js.
65% building 495/532 modules 37 active ...odules/core-js/internals/is-regexp.jsYou did not set any plugins, parser, or stringifier. Right now, PostCSS does nothing. Pick plugins for your case on https://www.postcss.parts/ and use them in postcss.config.js.
65% building 496/532 modules 36 active ...odules/core-js/internals/is-regexp.jsYou did not set any plugins, parser, or stringifier. Right now, PostCSS does nothing. Pick plugins for your case on https://www.postcss.parts/ and use them in postcss.config.js.
66% building 497/532 modules 35 active ...odules/core-js/internals/is-regexp.jsYou did not set any plugins, parser, or stringifier. Right now, PostCSS does nothing. Pick plugins for your case on https://www.postcss.parts/ and use them in postcss.config.js.
66% building 498/532 modules 34 active ...odules/core-js/internals/is-regexp.jsYou did not set any plugins, parser, or stringifier. Right now, PostCSS does nothing. Pick plugins for your case on https://www.postcss.parts/ and use them in postcss.config.js.
66% building 499/532 modules 33 active ...odules/core-js/internals/is-regexp.jsYou did not set any plugins, parser, or stringifier. Right now, PostCSS does nothing. Pick plugins for your case on https://www.postcss.parts/ and use them in postcss.config.js.
66% building 500/532 modules 32 active ...odules/core-js/internals/is-regexp.jsYou did not set any plugins, parser, or stringifier. Right now, PostCSS does nothing. Pick plugins for your case on https://www.postcss.parts/ and use them in postcss.config.js.
66% building 501/532 modules 31 active ...odules/core-js/internals/is-regexp.jsYou did not set any plugins, parser, or stringifier. Right now, PostCSS does nothing. Pick plugins for your case on https://www.postcss.parts/ and use them in postcss.config.js.
66% building 502/532 modules 30 active ...odules/core-js/internals/is-regexp.jsYou did not set any plugins, parser, or stringifier. Right now, PostCSS does nothing. Pick plugins for your case on https://www.postcss.parts/ and use them in postcss.config.js.
66% building 503/532 modules 29 active ...odules/core-js/internals/is-regexp.jsYou did not set any plugins, parser, or stringifier. Right now, PostCSS does nothing. Pick plugins for your case on https://www.postcss.parts/ and use them in postcss.config.js.
66% building 505/532 modules 27 active ...odules/core-js/internals/is-regexp.jsYou did not set any plugins, parser, or stringifier. Right now, PostCSS does nothing. Pick plugins for your case on https://www.postcss.parts/ and use them in postcss.config.js.
67% building 506/532 modules 26 active ...odules/core-js/internals/is-regexp.jsYou did not set any plugins, parser, or stringifier. Right now, PostCSS does nothing. Pick plugins for your case on https://www.postcss.parts/ and use them in postcss.config.js.
67% building 507/532 modules 25 active ...odules/core-js/internals/is-regexp.jsYou did not set any plugins, parser, or stringifier. Right now, PostCSS does nothing. Pick plugins for your case on https://www.postcss.parts/ and use them in postcss.config.js.
67% building 508/532 modules 24 active ...odules/core-js/internals/is-regexp.jsYou did not set any plugins, parser, or stringifier. Right now, PostCSS does nothing. Pick plugins for your case on https://www.postcss.parts/ and use them in postcss.config.js.
68% building 519/535 modules 16 active ...core-js/modules/es.symbol.iterator.jsYou did not set any plugins, parser, or stringifier. Right now, PostCSS does nothing. Pick plugins for your case on https://www.postcss.parts/ and use them in postcss.config.js.
68% building 520/535 modules 15 active ...core-js/modules/es.symbol.iterator.jsYou did not set any plugins, parser, or stringifier. Right now, PostCSS does nothing. Pick plugins for your case on https://www.postcss.parts/ and use them in postcss.config.js.
68% building 521/537 modules 16 active ...es/core-js/internals/string-repeat.jsYou did not set any plugins, parser, or stringifier. Right now, PostCSS does nothing. Pick plugins for your case on https://www.postcss.parts/ and use them in postcss.config.js.
68% building 522/537 modules 15 active ...es/core-js/internals/string-repeat.jsYou did not set any plugins, parser, or stringifier. Right now, PostCSS does nothing. Pick plugins for your case on https://www.postcss.parts/ and use them in postcss.config.js.
68% building 523/537 modules 14 active ...es/core-js/internals/string-repeat.jsYou did not set any plugins, parser, or stringifier. Right now, PostCSS does nothing. Pick plugins for your case on https://www.postcss.parts/ and use them in postcss.config.js.
68% building 528/542 modules 14 active ...js/internals/regexp-sticky-helpers.jsYou did not set any plugins, parser, or stringifier. Right now, PostCSS does nothing. Pick plugins for your case on https://www.postcss.parts/ and use them in postcss.config.js.
68% building 537/549 modules 12 active ....vue?vue&type=style&index=0&lang=css&You did not set any plugins, parser, or stringifier. Right now, PostCSS does nothing. Pick plugins for your case on https://www.postcss.parts/ and use them in postcss.config.js.
68% building 538/549 modules 11 active ....vue?vue&type=style&index=0&lang=css&You did not set any plugins, parser, or stringifier. Right now, PostCSS does nothing. Pick plugins for your case on https://www.postcss.parts/ and use them in postcss.config.js.
68% building 539/549 modules 10 active ....vue?vue&type=style&index=0&lang=css&You did not set any plugins, parser, or stringifier. Right now, PostCSS does nothing. Pick plugins for your case on https://www.postcss.parts/ and use them in postcss.config.js.
69% building 544/552 modules 8 active ...ntime/helpers/esm/nonIterableSpread.jsYou did not set any plugins, parser, or stringifier. Right now, PostCSS does nothing. Pick plugins for your case on https://www.postcss.parts/ and use them in postcss.config.js.
69% building 584/588 modules 4 active ...r.vue?vue&type=style&index=0&lang=css&You did not set any plugins, parser, or stringifier. Right now, PostCSS does nothing. Pick plugins for your case on https://www.postcss.parts/ and use them in postcss.config.js.
69% building 587/588 modules 1 active ...r.vue?vue&type=style&index=0&lang=css&You did not set any plugins, parser, or stringifier. Right now, PostCSS does nothing. Pick plugins for your case on https://www.postcss.parts/ and use them in postcss.config.js.
98% after emitting CopyPlugin

 DONE  Compiled successfully in 6173ms                                   9:49:33

  App running at:
  - Local:   http://localhost:8080 
  - Network: http://192.168.106.66:8080

  Note that the development build is not optimized.
  To create a production build, run npm run build.

`

**Comment by Inventsable** [comment]
If you're opening `localhost:8080` inside a Chrome window (*not the CEF Client*) you need to follow the steps in the documentation linked [Use in Browser](https://github.com/battleaxedotco/bombino-brutalism-router#use-in-browser). You would open the debug port of your app noted in the `.debug` file in your CEF Client, not `localhost:8080` (this is for iframe hot reloading of the panel, not for debugging). You would open `localhost:8888` (since you chose this in prompt) in the CEF to see a console and devtools, but otherwise never need to touch `localhost:8080` and just follow the steps that bombino tells you:

* Run `npm run serve`
* Restart your host application and find in Window > Extensions

Panels by default are only set up for running directly in the Adobe app. Running them in a Chrome window requires an additional step and is opt in, noted in the Use in Browser and Common Errors section of each template.

**Comment by tiandiyiqi** [comment]
OK .
The problem is solved.
Thanks!

**Comment by Inventsable** [comment]
No worries! Thanks for filing the issue, future users will hopefully notice and adjust (why I edited your title to the exact error and context).

Going to close this, let me know if you have any more trouble
